version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Configure Gradle
          command: |
#            cd android
            echo $KEYSTORE_B64 | base64 -d > ./adbshellkit.keystore
            echo $KEYSTORE_PROPERTIES_B64 | base64 -d > keystore.properties
#            if [[ $KEYSTORE ]]; then
#              echo $KEYSTORE_BASE64 | base64 --decode > ./app/$KEYSTORE
#              echo -e "KEYSTORE=$KEYSTORE" >> ./gradle.properties
#              echo -e "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> ./gradle.properties
#              echo -e "KEY_ALIAS=$KEY_ALIAS" >> ./gradle.properties
#              echo -e "KEY_PASSWORD=$KEYSTORE_PASSWORD" >> ./gradle.properties
#            fi
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples